export default {
  LOAD_PRODUCTS_REQUEST: 'LOAD_PRODUCTS_REQUEST',
  LOAD_CATEGORIES_REQUEST: 'LOAD_CATEGORIES_REQUEST',
  LOAD_PRODUCTS_SUCCESS: 'LOAD_PRODUCTS_SUCCESS',
  LOAD_CATEGORIES_SUCCESS: 'LOAD_CATEGORIES_SUCCESS',
  LOAD_PRODUCTS_ERROR: 'LOAD_PRODUCTS_ERROR',
  LOAD_CATEGORIES_ERROR: 'LOAD_CATEGORIES_ERROR',
  API_URL_DEV: 'http://localhost:3000/api/',
  SELECTED: 'selected',
  URL_CHANGE: 'URL_CHANGE',
  DOC_TITLE_CHANGE: 'DOC_TITLE_CHANGE'
};